
    CREATE TABLE IF NOT EXISTS `junkissas` (
        `id` int unsigned NOT NULL AUTO_INCREMENT,
        `name` varchar(255) NOT NULL COMMENT '店名',
        `prefecture_id` int NULL COMMENT '都道府県id',
        `address_1` varchar(45) NULL COMMENT '住所1(区市町村)',
        `address_2` varchar(45) NULL COMMENT '住所2(町名番地)',
        `address_3` varchar(45) NULL COMMENT '住所3(建物名)',
        `access_info` text COMMENT 'アクセス',
        `phone_number` varchar(20) NULL COMMENT '電話番号',
        `web_page` text COMMENT 'ホームページ',
        `business_hours` varchar(255) NULL COMMENT '営業時間',
        `regular_holiday` varchar(255) NULL COMMENT '定休日',
        `remark` text COMMENT '補足情報',
        `menu_info` text COMMENT 'メニュー情報',
        `year_of_establishment` int NULL COMMENT '創業年',
        `type_of_management` int NOT NULL DEFAULT '0' COMMENT '経営形態',
        `has_home_roasting` int NOT NULL DEFAULT '0' COMMENT '自家焙煎',
        `has_paper_drip` int NOT NULL DEFAULT '0' COMMENT 'ペーパードリップ',
        `has_nel_drip` int NOT NULL DEFAULT '0' COMMENT 'ネルドリップ',
        `has_siphon` int NOT NULL DEFAULT '0' COMMENT 'サイフォン',
        `has_french_press` int NOT NULL DEFAULT '0' COMMENT 'フレンチプレス',
        `has_aero_press` int NOT NULL DEFAULT '0' COMMENT 'エアロプレス',
        `has_espresso` int NOT NULL DEFAULT '0' COMMENT 'エスプレッソ',
        `has_cold_brew` int NOT NULL DEFAULT '0' COMMENT '水出し',
        `has_light_meal` int NOT NULL DEFAULT '0' COMMENT '軽食あり',
        `has_morning_set` int NOT NULL DEFAULT '0' COMMENT 'モーニングセットあり',
        `has_dessert` int NOT NULL DEFAULT '0' COMMENT 'デザートあり',
        `has_alcohol` int NOT NULL DEFAULT '0' COMMENT 'アルコールあり',
        `has_smoking_seat` int NOT NULL DEFAULT '0' COMMENT '喫煙席あり',
        `has_comic` int NOT NULL DEFAULT '0' COMMENT '漫画あり',
        `has_classical_music` int NOT NULL DEFAULT '0' COMMENT '名曲あり',
        `has_game_machine` int NOT NULL DEFAULT '0' COMMENT 'ゲーム台あり',
        `has_karaoke` int NOT NULL DEFAULT '0' COMMENT 'カラオケあり',
        `closed_flg` int NOT NULL DEFAULT '0' COMMENT '閉店フラグ',
        `active` int NOT NULL DEFAULT '1' COMMENT 'アクティブ',
        `created_by` int NULL comment '登録ユーザid',
        `created_at` timestamp NULL COMMENT '登録日時',
        `updated_by` int NULL comment '更新ユーザid',
        `updated_at` timestamp NULL COMMENT '更新日時',
        PRIMARY KEY (`id`)
    )
    default character set utf8mb4
    collate 'utf8mb4_unicode_ci';