
    CREATE TABLE IF NOT EXISTS `_mst_prefectures` (
        `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
        `area_id` INT NOT NULL COMMENT 'エリアID',
        `name` VARCHAR(20) NOT NULL COMMENT '都道府県名',
        `name_en` varchar(30) NULL,
        `active` INT NOT NULL DEFAULT 1 COMMENT 'アクティブ',
        `created_at` TIMESTAMP NULL COMMENT '登録日時',
        `updated_at` TIMESTAMP NULL COMMENT '更新日時'
    )
    default character set utf8mb4
    collate 'utf8mb4_unicode_ci';

    INSERT INTO `_mst_prefectures` VALUES
        (1,  1, '北海道',   'hokkaido',     1, now(), now()),
        (2,  1, '青森県',   'aomori',       1, now(), now()),
        (3,  1, '岩手県',   'iwate',        1, now(), now()),
        (4,  1, '宮城県',   'miyagi',       1, now(), now()),
        (5,  1, '秋田県',   'akita',        1, now(), now()),
        (6,  1, '山形県',   'yamagata',     1, now(), now()),
        (7,  1, '福島県',   'hukushima',    1, now(), now()),
        (8,  2, '茨城県',   'ibaraki',      1, now(), now()),
        (9,  2, '栃木県',   'tochigi',      1, now(), now()),
        (10, 2, '群馬県',   'gunma',        1, now(), now()),
        (11, 2, '埼玉県',   'saitama',      1, now(), now()),
        (12, 2, '千葉県',   'chiba',        1, now(), now()),
        (13, 2, '東京都',   'tokyo',        1, now(), now()),
        (14, 2, '神奈川県', 'kanagawa',     1, now(), now()),
        (15, 3, '新潟県',   'niigata',      1, now(), now()),
        (16, 3, '富山県',   'toyama',       1, now(), now()),
        (17, 3, '石川県',   'ishikawa',     1, now(), now()),
        (18, 3, '福井県',   'hukui',        1, now(), now()),
        (19, 3, '山梨県',   'yamanashi',    1, now(), now()),
        (20, 3, '長野県',   'nagano',       1, now(), now()),
        (21, 4, '岐阜県',   'gihu',         1, now(), now()),
        (22, 4, '静岡県',   'shizuoka',     1, now(), now()),
        (23, 4, '愛知県',   'aichi',        1, now(), now()),
        (24, 4, '三重県',   'mie',          1, now(), now()),
        (25, 5, '滋賀県',   'shiga',        1, now(), now()),
        (26, 5, '京都府',   'kyoto',        1, now(), now()),
        (27, 5, '大阪府',   'osaka',        1, now(), now()),
        (28, 5, '兵庫県',   'hyogo',        1, now(), now()),
        (29, 5, '奈良県',   'nara',         1, now(), now()),
        (30, 5, '和歌山県', 'wakayama',     1, now(), now()),
        (31, 6, '鳥取県',   'tottori',      1, now(), now()),
        (32, 6, '島根県',   'shimane',      1, now(), now()),
        (33, 6, '岡山県',   'okayama',      1, now(), now()),
        (34, 6, '広島県',   'hiroshima',    1, now(), now()),
        (35, 6, '山口県',   'yamaguchi',    1, now(), now()),
        (36, 6, '徳島県',   'tokushima',    1, now(), now()),
        (37, 6, '香川県',   'kagawa',       1, now(), now()),
        (38, 6, '愛媛県',   'ehime',        1, now(), now()),
        (39, 6, '高知県',   'kochi',        1, now(), now()),
        (40, 7, '福岡県',   'hukuoka',      1, now(), now()),
        (41, 7, '佐賀県',   'saga',         1, now(), now()),
        (42, 7, '長崎県',   'nagasaki',     1, now(), now()),
        (43, 7, '熊本県',   'kumamoto',     1, now(), now()),
        (44, 7, '大分県',   'oita',         1, now(), now()),
        (45, 7, '宮崎県',   'miyazaki',     1, now(), now()),
        (46, 7, '鹿児島県', 'kagoshima',    1, now(), now()),
        (47, 7, '沖縄県',   'okinawa',      1, now(), now());
